const LOAD_USERS = 'LOAD_USERS';
const CREATE_USER = 'CREATE_USER';

const LOAD_HOBBIES = 'LOAD_HOBBIES';
const CREATE_HOBBY = 'CREATE_HOBBY';

export {
  LOAD_USERS,
  CREATE_USER,
  LOAD_HOBBIES,
  CREATE_HOBBY
};
